export const captchasData = [
    {
        imagePath: 'assets/gorilla_basketball.jpg',
        rows: 8,
        cols: 8,
        prompt1: 'Select all squares with',
        prompt2: 'a basketball',
        selected_correct: [
            [0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0],
            [0,0,1,1,0,0,0,0],
            [0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0],
        ],
        unselected_correct: [],
        selected_trap: [],
        unselected_trap: [],
        attribution: "Gorilla basketball experiment - AI-generated",
        message_intermission_correct: "Great, you see the big picture",
        message_intermission_trap: "But did you see the gorilla?",
    },
    {
        imagePath: 'assets/scandalous.jpg',
        rows: 4,
        cols: 4,
        prompt1: 'Select all images with',
        prompt2: 'ankle',
        selected_correct: [],
        unselected_correct: [],
        selected_trap: [],
        unselected_trap: [],
        attribution: "Gorilla basketball experiment - AI-generated",
        message_intermission_correct: "Great, you see the big picture",
        message_intermission_trap: "But did you see the gorilla?",
    },
    {
        imagePath: 'assets/metro2.jpg',
        rows: 4,
        cols: 4,
        prompt1: 'Select all squares with',
        prompt2: 'free seats',
        selected_correct: [
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
        ],
        unselected_correct: [],
        selected_trap: [],
        unselected_trap: [],
        attribution: "Own work – Yunseon and Konsta",
        message_intermission_correct: "Great, you understand social distancing",
        message_intermission_trap: "Huh, give us some personal space!",
    },
];
